apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "parseable-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "parseable-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "parseable-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "parseable-operator.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "parseable-operator.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 10
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --health-probe-bind-address=:8081
            {{- if .Values.leaderElection }}
            - --leader-elect
            {{- end }}
          env:
            - name: PB_RECONCILE_WAIT
              value: {{ .Values.reconcileWait | quote }}
            {{- with .Values.autoscalerReconcileWait }}
            - name: PB_AUTOSCALER_RECONCILE_WAIT
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.chaosReconcileWait }}
            - name: PB_CHAOS_RECONCILE_WAIT
              value: {{ . | quote }}
            {{- end }}
            {{- with .Values.denyList }}
            - name: DENY_LIST
              value: {{ . | quote }}
            {{- end }}
          ports:
            - name: health
              containerPort: 8081
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
